### ISSUE TITLE
Doesn't Work with Cygwin

### ISSUE THREAD

**Issue by brianpham** [luchihoratiu/debug-via-ssh#13]
I am seeing the following message when trying to use this with cygwin installed. https://github.com/cygwin/cygwin-install-action Does anyone know what I can do to work around this?

```
D:\a\_temp\6a4be032-3128-4d46-8f83-a5b27c4774fe.sh: line 12: syntax error: unexpected end of file
Error: Process completed with exit code 2.
```

To Reproduce:
1. Add the following step to the workflow. 
```
runs-on: windows-2019
- uses: cygwin/cygwin-install-action@master

- name: Create SSH Session
      uses: luchihoratiu/debug-via-ssh@main
      with:
          NGROK_AUTH_TOKEN: "<>"
          SSH_PASS: "<>"
```

2. The `Create Debug Session` will fail with the following error. `D:\a\_temp\6a4be032-3128-4d46-8f83-a5b27c4774fe.sh: line 12: syntax error: unexpected end of file
Error: Process completed with exit code 2.`
